"""Chinese help manual command."""
from __future__ import annotations

try:
    from novel_pipeline.version import get_version
except ImportError:
    from version import get_version


def cmd_scc_help():
    """打印中文用户手册。"""
    print("=" * 68)
    print("  小说写作流水线 — 操作手册")
    v = get_version()
    print(f"  Write Engine {v}")
    print("=" * 68)
    print()
    print("  novel.py 是所有操作的统一入口。")
    print()
    print("  ── Hermes/Agent 用户 ──")
    print("  如果你是 Hermes Agent 用户，可以直接用自然语言与我对话：")
    print("  · 说「我要写第3章」→ 我会检查上下文并生成任务卡")
    print("  · 说「添加大纲」→ 我会引导你上传或粘贴大纲内容")
    print("  · 说「审稿第1章」→ 我会运行 Agent 陪审团审查")
    print("  · 说「导出小说」→ 我会帮你导出 Markdown")
    print("  · 说「菜单」→ 我会显示交互式中文菜单")
    print()
    print("  ── CLI/终端用户 ──")
    print("  以下按功能分类列出常用命令。")
    print()

    # ── 1. 新用户从这里开始 ──
    print("  " + "─" * 60)
    print("  【新用户从这里开始】")
    print("  " + "─" * 60)
    print("  python novel.py init                初始化项目（目录 + 数据库 + 配置）")
    print("  python novel.py status              检查环境状态（Python/配置/文件完整性）")
    print("  python novel.py status --detail     详细诊断模式")
    print("  python novel.py demo                运行演示流水线（创建示例章节并跑全部守卫）")
    print("  python novel.py pre <章节号>         生成写前任务卡（上下文/伏笔/规则）")
    print("  python novel.py post <章节号>        写后守卫检查 + 入库")
    print("  python novel.py board               只读项目看板（总览状态）")
    print()

    # ── 2. 大纲管理 ──
    print("  " + "─" * 60)
    print("  【大纲管理】outline")
    print("  " + "─" * 60)
    print("  python novel.py outline add <文件>       添加大纲（自动相似度检测）")
    print("  python novel.py outline import <文件>    导入大纲（--title 必须指定标题）")
    print("  python novel.py outline list             列出当前工作区所有大纲")
    print("  python novel.py outline current          显示当前激活大纲")
    print("  python novel.py outline switch <id>      切换激活大纲")
    print("  python novel.py outline diff <id1> <id2> 对比两个大纲（相似度分析）")
    print("  python novel.py outline rollback <id>    回滚大纲到上一版本")
    print("  python novel.py outline compare <文件>    对比文件与当前激活大纲")
    print("  python novel.py outline delete <id>      删除指定大纲")
    print()

    # ── 3. 数据库管理 ──
    print("  " + "─" * 60)
    print("  【数据库管理】db")
    print("  " + "─" * 60)
    print("  python novel.py db init              初始化 workspace 目录结构")
    print("  python novel.py db list              列出所有 DB slot（★=当前活跃）")
    print("  python novel.py db current           显示当前活跃 DB slot")
    print("  python novel.py db info              显示当前 slot 详细信息")
    print("  python novel.py db new --name <名>    创建新 DB slot")
    print("  python novel.py db use <slot_id>     切换 DB slot")
    print("  python novel.py db backup            备份当前 slot 的 project.json")
    print("  python novel.py db delete <slot_id>  删除指定 DB slot（不能删当前活跃的）")
    print("  python novel.py db restore <slot_id> 从备份恢复 DB slot")
    print()

    # ── 4. Agent 陪审团 ──
    print("  " + "─" * 60)
    print("  【Agent 陪审团】agents")
    print("  " + "─" * 60)
    print("  python novel.py agents review <章> --mode light   轻量模式审查（快）")
    print("  python novel.py agents review <章> --mode full    完整模式审查（详细）")
    print("  python novel.py agents review <章> --genre xianxia  指定题材风格")
    print()

    # ── 5. Story Contract ──
    print("  " + "─" * 60)
    print("  【Story Contract 故事合同系统】story")
    print("  " + "─" * 60)
    print("  python novel.py story init                 初始化 .story/ 目录")
    print("  python novel.py story contract <章>         生成章节合同（约束 + 伏笔）")
    print("  python novel.py story commit <章>           生成章节提交记录")
    print("  python novel.py story health                故事链健康检查")
    print("  python novel.py post <章> --story           写后守卫 + 自动生成 commit")
    print()

    # ── 6. 记忆与规则 ──
    print("  " + "─" * 60)
    print("  【记忆与规则】query / learn")
    print("  " + "─" * 60)
    print("  python novel.py query <问题>        查询项目记忆（角色/伏笔/世界观）")
    print("  python novel.py learn list          列出已学写作规则")
    print("  python novel.py learn add <规则>    添加写作规则")
    print("  python novel.py learn remove <编号> 删除写作规则")
    print()

    # ── 7. 导出与报告 ──
    print("  " + "─" * 60)
    print("  【导出与报告】report / export")
    print("  " + "─" * 60)
    print("  python novel.py report                  显示最近守卫报告")
    print("  python novel.py guards                  列出注册的守卫及状态")
    print("  python novel.py check <文件>            对指定章节文件运行守卫检查")
    print("  python novel.py export --slug <id>      导出为 Markdown（默认）")
    print("  python novel.py export --slug <id> --format txt  导出为纯文本")
    print("  python novel.py wc <章节号|文件>         统计中文字数")
    print()

    # ── 8. 其他工具 ──
    print("  " + "─" * 60)
    print("  【其他工具】genre / style / rag / review")
    print("  " + "─" * 60)
    print("  python novel.py genre list              列出可用题材包")
    print("  python novel.py genre show <id>         查看题材包详情")
    print("  python novel.py style list              列出可用风格包")
    print("  python novel.py style show <id>         查看风格包详情")
    print("  python novel.py rag status              查看 RAG 状态（向量/全文搜索）")
    print("  python novel.py rag query <问题>        语义搜索小说数据库")
    print("  python novel.py review <章>             运行守卫审查")
    print()

    # ── 9. 常见问题 ──
    print("  " + "━" * 60)
    print("  【常见问题 FAQ】")
    print("  " + "━" * 60)
    print()
    print("  Q: 为什么 pre/post/write 提示「没有激活的大纲」？")
    print("  A: 必须先添加大纲才能开始写作。")
    print("     1) 把大纲 .txt 文件放到「大纲」文件夹（如 D:\\小说\\大纲\\）")
    print("     2) 执行: python novel.py outline add D:\\小说\\大纲\\大纲.txt")
    print("     或在 Hermes 里直接说「添加大纲」")
    print()
    print("  Q: 如何开始一部新小说？")
    print("  A: 推荐流程：")
    print("     1) 在 D:\\小说\\大纲\\ 下创建小说大纲 .txt 文件")
    print("     2) python novel.py outline add <大纲路径>    # 自动检测相似度，不同小说自动创建新 slot")
    print("     3) python novel.py pre 1                      # 生成第1章任务卡")
    print("     4) python novel.py post 1                     # 写完后入库 + 守卫检查")
    print()
    print("  Q: outline upgrade 和 db new 有什么区别？")
    print("  A: 同一部小说的新大纲用 outline add（自动检测相似度，建议升级）")
    print("     不同小说用 db new 创建独立工作区（数据互不干扰）")
    print()
    print("  Q: 数据库文件在哪里？")
    print("  A: 每个 DB slot 在 workspace/<slot_id>/ 下有独立的 novel.db。")
    print("     例如当前活跃 slot 的数据库: workspace/<active_slot>/novel.db")
    print("     config.json 中 db_path 字段也可以指定自定义路径。")
    print()
    print("  Q: 如何查看完整帮助？")
    print("  A: python novel.py --help      查看所有命令列表")
    print("     python novel.py <命令> --help 查看具体命令的用法")
    print("     python novel.py menu         进入交互式菜单")
    print()
    print("  " + "━" * 60)
    print("  使用 python novel.py menu 进入交互式菜单")
    print("  " + "━" * 60)
    print()
    return 0
